version: "3.11"

services:
  sample_backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://sample:28G>t@&8PBPe@db:5432/sample_db  # Updated port to 5434
    depends_on:
      - db

  db:
    image: postgres:13.5-alpine
    restart: always
    env_file: .env
    ports:
      - "5434:5432"  # Mapping container port 5432 to host port 5434
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
