stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG

build:
  stage: build
  tags:
    - devops
  script:
    - echo $DOCKER_IMAGE
    - echo $CI_REGISTRY_USER $CI_JOB_TOKEN $CI_REGISTRY
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -f Dockerfile -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:latest

deploy:
  stage: deploy
  tags:
    - devops
  script:
    - echo $CI_JOB_TOKEN
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "sudo bash /srv/django/dett_backend/dett-back-end/scripts/deploy.sh '$CI_JOB_TOKEN' '$CI_REGISTRY' '$CI_REGISTRY_USER'" 

